adviceFoolReading = [
    {'name' : 'The Fool', 'meaning' : 'The Fool advises that you lighten up. Let yourself be spontaneous enough to stretch beyond the realm of logic. There is no advantage to be gained by thinking you possess the knowledge, power, or control to direct reality. Open and receive without question, instead of trying to manage what\'s happening right now. The Fool has no ambition to manipulate a specific outcome. Just be happy to be part of the whole. \nRelease any demands or expectations. Give your complete attention to events as they are occurring in the present moment.'},
]
adviceMagicianReading = [
    {'name' : 'The Magician', 'meaning' : 'Have faith in your innate creativity. The Magician advises you give your questioning nature and free-associating mind plenty of room to explore the subject at hand. Behave just as if you were an open-minded and curious scientist. Through this process, you may bring freshness and clarity into the situation that is both stimulating and catalytic. \nYou do not have to understand it all intellectually. Besides, intuition is your ace in the hole. Respond in a spontaneous manner to what is right in front of you. There is no reason to hold yourself back. Your natural urges are exactly what is needed, and, your ingenuous timing and elegant style will help smooth over any awkwardness.'},
]
advicePriestessReading = [
    {'name' : 'The High Priestess', 'meaning' : 'The High Priestess advises you to adhere to your chosen spiritual practice on a more regular basis. If you want the benefits of evolution, you\'ll have to cooperate with spirit. We all have distractions, demands -- a whole life full of reasons why we cannot find the time to retreat into our inner sanctum. \nUntil you consider this as vital to your well-being as the need to eat and sleep, you are likely to be eternally restless and deeply dissatisfied. A spiritual routine that suits your temperament, practiced every day, is the most trustworthy path to freedom.'},
]
