loveFoolReading = [
    {'name' : 'The Fool', 'meaning' : 'The Fool is associated with circumstances that are unique, unpredictable and inscrutable -- like one who is suspended between realities. The Fool is often portrayed as an empty headed simpleton unaware of the forces that move him to and fro, following his impulses. But tradition tells us that this Fool has a secret that protects him: the magic of synchronicity. He proceeds without calculation, spontaneously, without hesitation or resistance. \nIf you trust in your own mystery and that of Divine Providence, you can step into a new realm of opportunities for you and your potential love interest. For now, trust your instincts. If you have no expectations, you have nothing to lose.'}
    ]
loveMagicianReading = [
    {'name' : 'The Magician', 'Meaning' : 'The Magus symbolizes imagination, creativity and an inventive nature. Your unique intelligence and talent for clever experimentation is a valuable asset for keeping your future relationship fresh and alive. The Magus serves as a catalyst and change agent. His influence is a fresh breeze blowing through any situation. So be playful, and stay open. Don\'t limit yourself, the possibilities are endless. Try things, see what happens and correct your course as you go. Tease open the minds of those who are watching to see what you will do - including your potential love interest.'}
]
lovePriestessReading = [
    {'name' : 'The High Priestess', 'meaning' : 'The High Priestess craves deep communion with Nature and attunement with cosmic law. She wants to be far from the hustle and bustle, the daily traffic of life, so she can meditate. \nGet your ego out of the way and let your mind become attuned to a more subtle, spiritual view. Seek to divine the principles behind seemingly chaotic events, daily life or society in general. Take some time out. Write in your journal. Sit on a mountaintop. Work with your feelings until you become reflective like the smooth calm of still waters at dawn.'}
]
